---
resources:
  - name: springboot-src
    type: git
    source:
      uri: https://github.com/expertsystemhk/SpringBootWebApplication.git
      branch: develop

  - name: springboot-docker-image
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/springboot

jobs:
  - name: publish
    public: true
    plan:
      - get: springboot-src
      - put: springboot-docker-image
        params:
          build: springboot-src
      - task: run
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((docker-hub-username))/springboot
          run:
            path: echo
            args: [hello world]
          params:
            NAME: ((docker-hub-username))
